In [1]:
import urllib2
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import *

In [2]:
def read_data():
    x = ["Draw #", 'Draw Date1', 'Draw Date2', 'Draw Date3','Draw Date4', 'Number_1', 'Number_2', 'Number_3', 'Number_4', 'Number_5', 'Powerball']
    df = pd.read_csv("DownloadAllNumbers.txt", delim_whitespace=True, skiprows=1, names=x)
    df['Date'] = df['Draw Date1'] + ' ' + df['Draw Date2'] + ' ' + df['Draw Date3'] + ' '+ df['Draw Date4']
    df['Year'] = df['Draw Date4']
    df['Month'] = df['Draw Date2']
    df = df[1:]
    df
    df = df.drop(columns=['Draw Date1', 'Draw Date2', 'Draw Date3', 'Draw Date4'])
    df['Number_3'] = pd.to_numeric(df['Number_3'])
    df['Number_2'] = pd.to_numeric(df['Number_2'])
    df['Number_1'] = pd.to_numeric(df['Number_1'])
    return df

data_df = read_data()
data_df

,Draw #,Number_1,Number_2,Number_3,Number_4,Number_5,Powerball,Date,Year,Month
1,637,33,68,61,17.0,7.0,4.0,"Wed. May 15, 2019",2019,May
2,636,40,9,8,6.0,37.0,26.0,"Sat. May 11, 2019",2019,May
3,635,66,64,45,53.0,1.0,3.0,"Wed. May 08, 2019",2019,May
4,634,30,6,23,16.0,61.0,2.0,"Sat. May 04, 2019",2019,May
5,633,66,28,23,56.0,5.0,17.0,"Wed. May 01, 2019",2019,May
6,632,45,29,62,41.0,2.0,6.0,"Sat. Apr 27, 2019",2019,Apr
7,631,35,65,32,36.0,6.0,4.0,"Wed. Apr 24, 2019",2019,Apr
8,630,3,63,27,65.0,30.0,1.0,"Sat. Apr 20, 2019",2019,Apr
9,629,15,46,66,17.0,1.0,15.0,"Wed. Apr 17, 2019",2019,Apr
10,628,17,26,32,4.0,49.0,10.0,"Sat. Apr 13, 2019",2019,Apr
11,627,39,12,21,23.0,67.0,6.0,"Wed. Apr 10, 2019",2019,Apr
12,626,33,43,60,59.0,15.0,8.0,"Sat. Apr 06, 2019",2019,Apr
13,625,25,16,32,49.0,19.0,18.0,"Wed. Apr 03, 2019",2019,Apr
14,624,54,52,21,64.0,68.0,4.0,"Sat. Mar 30, 2019",2019,Mar
15,623,44,62,20,37.0,16.0,12.0,"Wed. Mar 27, 2019",2019,Mar
16,622,66,52,60,24.0,25.0,5.0,"Sat. Mar 23, 2019",2019,Mar
17,621,10,53,50,63.0,14.0,21.0,"Wed. Mar 20, 2019",2019,Mar
18,620,67,30,34,39.0,53.0,11.0,"Sat. Mar 16, 2019",2019,Mar
19,619,69,36,45,47.0,18.0,14.0,"Wed. Mar 13, 2019",2019,Mar
20,618,45,5,59,55.0,6.0,14.0,"Sat. Mar 09, 2019",2019,Mar
21,617,21,35,10,6.0,46.0,23.0,"Wed. Mar 06, 2019",2019,Mar
22,616,27,68,25,19.0,1.0,21.0,"Sat. Mar 02, 2019",2019,Mar
23,615,49,31,59,42.0,21.0,23.0,"Wed. Feb 27, 2019",2019,Feb
24,614,32,4,20,6.0,14.0,13.0,"Sat. Feb 23, 2019",2019,Feb
25,613,50,52,49,51.0,27.0,2.0,"Wed. Feb 20, 2019",2019,Feb
26,612,48,30,41,64.0,29.0,1.0,"Sat. Feb 16, 2019",2019,Feb
27,611,2,24,8,69.0,14.0,26.0,"Wed. Feb 13, 2019",2019,Feb
28,610,7,39,2,3.0,1.0,25.0,"Sat. Feb 09, 2019",2019,Feb
29,609,13,28,5,63.0,38.0,21.0,"Wed. Feb 06, 2019",2019,Feb
30,608,10,43,17,18.0,65.0,13.0,"Sat. Feb 02, 2019",2019,Feb
...,...,...,...,...,...,...,...,...,...,...
608,30,14,27,58,25.0,38.0,6.0,"Sat. Jul 20, 2013",2013,Jul
609,29,22,1,42,38.0,34.0,17.0,"Wed. Jul 17, 2013",2013,Jul
610,28,8,37,2,35.0,22.0,6.0,"Sat. Jul 13, 2013",2013,Jul
611,27,55,45,31,30.0,59.0,27.0,"Wed. Jul 10, 2013",2013,Jul
612,26,52,2,36,35.0,13.0,11.0,"Sat. Jul 06, 2013",2013,Jul
613,25,40,6,51,29.0,3.0,4.0,"Wed. Jul 03, 2013",2013,Jul
614,24,28,8,56,53.0,30.0,16.0,"Sat. Jun 29, 2013",2013,Jun
615,23,1,46,39,33.0,18.0,33.0,"Wed. Jun 26, 2013",2013,Jun
616,22,33,57,19,23.0,13.0,28.0,"Sat. Jun 22, 2013",2013,Jun
617,21,57,47,46,52.0,7.0,17.0,"Wed. Jun 19, 2013",2013,Jun
618,20,48,55,28,40.0,36.0,1.0,"Sat. Jun 15, 2013",2013,Jun
619,19,22,16,42,23.0,55.0,32.0,"Wed. Jun 12, 2013",2013,Jun
620,18,2,26,11,32.0,22.0,19.0,"Sat. Jun 08, 2013",2013,Jun
621,17,4,36,26,33.0,55.0,32.0,"Wed. Jun 05, 2013",2013,Jun
622,16,33,53,59,22.0,28.0,14.0,"Sat. Jun 01, 2013",2013,Jun
623,15,49,14,9,17.0,57.0,2.0,"Wed. May 29, 2013",2013,May
624,14,27,21,19,6.0,2.0,25.0,"Sat. May 25, 2013",2013,May
625,13,31,35,41,9.0,57.0,26.0,"Wed. May 22, 2013",2013,May
626,12,22,10,13,14.0,52.0,11.0,"Sat. May 18, 2013",2013,May
627,11,2,34,11,41.0,26.0,32.0,"Wed. May 15, 2013",2013,May
628,10,6,23,19,43.0,13.0,16.0,"Sat. May 11, 2013",2013,May
629,9,21,57,26,22.0,30.0,27.0,"Wed. May 08, 2013",2013,May
630,8,26,36,40,7.0,12.0,17.0,"Sat. May 04, 2013",2013,May
631,7,31,22,55,26.0,54.0,18.0,"Wed. May 01, 2013",2013,May
632,6,55,54,48,23.0,3.0,5.0,"Sat. Apr 27, 2013",2013,Apr
633,5,9,59,31,56.0,19.0,2.0,"Wed. Apr 24, 2013",2013,Apr
634,4,6,39,8,30.0,48.0,20.0,"Sat. Apr 20, 2013",2013,Apr
635,3,58,18,48,13.0,36.0,28.0,"Wed. Apr 17, 2013",2013,Apr
636,2,10,57,31,12.0,56.0,33.0,"Sat. Apr 13, 2013",2013,Apr
637,1,40,1,52,36.0,53.0,20.0,"Wed. Apr 10, 2013",2013,Apr

In [32]:
# data = loadtxt('data.txt',dtype=int,usecols=(4,)) #loading 5th column of csv file into array named data. 
# data = df['Powerball']
# plt.hist(data, bins=np.arange(data.min(), data.max()+1))
# df_top_freq = df.groupby(['Date', 'Draw #', 'Powerball'])['Powerball'].agg(
#     {"code_count": len}).sort_values(
#     "code_count", ascending=True).head(10).reset_index()

def best_guess_df(df, n=10, year=None, month=None):
    
    def filter_df(df, year=None, month=None):
#         if(year and month):
#             return df.loc[df['Year'] == str(year) and df['Month'] == str(month)]
        
        if(year):
            return df.loc[df['Year'] == str(year)]

        if(month):
            return df.loc[df['Month'] == str(month)]

        else:
            return df

    new_df = filter_df(df=df, year=year, month=month)

    def get_top(df, colname="Number_1", n=n):
        numdf = pd.DataFrame(index=range(0, n))
        countdf = df[colname].value_counts().nlargest(n)
        numdf[colname] = zip(countdf.index.values, countdf)
        return numdf, len(df[colname])

    num1, n1 = get_top(new_df, "Number_1")
    num2, n2 = get_top(new_df, "Number_2")
    num3, n3 = get_top(new_df, "Number_3")
    num4, n4 = get_top(new_df, "Number_4")
    num5, n5 = get_top(new_df, "Number_5")
    powerball, p = get_top(new_df, "Powerball")

    num_df = pd.DataFrame(columns=["Number_1", "Number_2", "Number_3", "Number_4", "Number_5", "Powerball"])

    num_df["Number_1"] = num1['Number_1']
    num_df["Number_2"] = num2['Number_2']
    num_df["Number_3"] = num3['Number_3']
    num_df["Number_4"] = num4['Number_4']
    num_df["Number_5"] = num5['Number_5']
    num_df["Powerball"] = powerball['Powerball']

    def best_guess(df):
        return str(df['Number_1'][0]) + ' ' + str(df['Number_2'][0]) + ' ' + str(df['Number_3'][0]) + ' ' + str(df['Number_4'][0]) + ' ' + str(df['Number_5'][0]) + ' ' + str(df['Powerball'][0])

    num_df['Best_Guess'] = num_df.apply(best_guess, axis=1)
    
    return num_df

best_df = best_guess_df(data_df[1:], n=20, year=2019, month='May')
best_df

,Number_1,Number_2,Number_3,Number_4,Number_5,Powerball,Best_Guess
0,"(66, 3)","(52, 3)","(8, 3)","(6.0, 4)","(1.0, 4)","(21.0, 3)",66 52 8 6.0 1.0 21.0
1,"(45, 2)","(65, 2)","(32, 3)","(64.0, 2)","(14.0, 3)","(6.0, 3)",45 65 32 64.0 14.0 6.0
2,"(15, 2)","(28, 2)","(21, 3)","(36.0, 2)","(6.0, 2)","(1.0, 3)",15 28 21 36.0 6.0 1.0
3,"(10, 2)","(30, 2)","(23, 2)","(23.0, 2)","(49.0, 2)","(12.0, 2)",10 30 23 23.0 49.0 12.0
4,"(50, 2)","(46, 2)","(59, 2)","(63.0, 2)","(8.0, 1)","(2.0, 2)",50 46 59 63.0 8.0 2.0
5,"(69, 1)","(43, 2)","(45, 2)","(29.0, 1)","(61.0, 1)","(4.0, 2)",69 43 45 29.0 61.0 4.0
6,"(7, 1)","(63, 1)","(20, 2)","(18.0, 1)","(5.0, 1)","(10.0, 2)",7 63 20 18.0 5.0 10.0
7,"(19, 1)","(9, 1)","(60, 2)","(53.0, 1)","(2.0, 1)","(26.0, 2)",19 9 60 53.0 2.0 26.0
8,"(21, 1)","(24, 1)","(62, 1)","(16.0, 1)","(30.0, 1)","(14.0, 2)",21 24 62 16.0 30.0 14.0
9,"(12, 1)","(16, 1)","(5, 1)","(56.0, 1)","(67.0, 1)","(23.0, 2)",12 16 5 56.0 67.0 23.0
10,"(13, 1)","(12, 1)","(7, 1)","(41.0, 1)","(15.0, 1)","(13.0, 2)",13 12 7 41.0 15.0 13.0
11,"(14, 1)","(6, 1)","(10, 1)","(31.0, 1)","(19.0, 1)","(24.0, 2)",14 6 10 31.0 19.0 24.0
12,"(3, 1)","(8, 1)","(12, 1)","(65.0, 1)","(68.0, 1)","(11.0, 1)",3 8 12 65.0 68.0 11.0
13,"(16, 1)","(26, 1)","(17, 1)","(17.0, 1)","(16.0, 1)","(5.0, 1)",16 26 17 17.0 16.0 5.0
14,"(17, 1)","(5, 1)","(2, 1)","(4.0, 1)","(25.0, 1)","(22.0, 1)",17 5 2 4.0 25.0 22.0
15,"(2, 1)","(68, 1)","(29, 1)","(66.0, 1)","(53.0, 1)","(18.0, 1)",2 68 29 66.0 53.0 18.0
16,"(67, 1)","(2, 1)","(25, 1)","(59.0, 1)","(3.0, 1)","(8.0, 1)",67 2 25 59.0 3.0 8.0
17,"(57, 1)","(25, 1)","(27, 1)","(49.0, 1)","(18.0, 1)","(15.0, 1)",57 25 27 49.0 18.0 15.0
18,"(56, 1)","(29, 1)","(34, 1)","(32.0, 1)","(46.0, 1)","(25.0, 1)",56 29 34 32.0 46.0 25.0
19,"(27, 1)","(27, 1)","(37, 1)","(37.0, 1)","(21.0, 1)","(17.0, 1)",27 27 37 37.0 21.0 17.0

In [ ]:
plt.hist(data, bins=np.arange(data.min(), data.max()+1))

In [ ]:


# s = df['Powerball'].groupby(df['Powerball']).value_counts()
# print(s)
# print(df_top_freq)